config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get "welcome/index"
  resources :coins

  root to: "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy!

    respond_to do |format|
      format.html { redirect_to coins_path, status: :see_other, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy!

    respond_to do |format|
      format.html { redirect_to mining_types_path, status: :see_other, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meu_nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <th><%= coin.description %></th>
    <th><%= coin.acronym %></th>
    <th><%= image_tag coin.url_image, size: "50x50" %></th>
  </tbody>
</table>

app/views/coins/_form.html.erb
<%= form_with(model: coin, class: "needs-validation") do |form| %>
  <% if coin.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>
      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :acronym, class: "form-label" %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :url_image, class: "form-label" %>
    <%= form.text_field :url_image, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :mining_type_id, class: "form-label" %>
    <%= form.select(:mining_type_id, @mining_type_options, {include_blank: "Selecione..."}, class: "form-select") %>
  </div>

  <div class="mt-3">
    <%= form.submit "Save Coin", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<% content_for :title, "Editing coin" %>

<div class="container mt-4">
    <h1 class="text-primary">Editing Coin</h1>

    <div class="card p-4 shadow-sm mt-3">
        <%= render "form", coin: @coin %>
    </div>

    <div class="mt-4">
        <%= link_to "Show this coin", @coin, class: "btn btn-info" %> |
        <%= link_to "Back to coins", coins_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Coins" %>

<h1 class="text-center text-primary">Coins</h1>

<div id="coins" class="container mt-4">
  <div class="row">
    <% @coins.each do |coin| %>
      <div class="col-md-4">
        <div class="card shadow-sm p-3 mb-4 bg-white rounded">
          <div class="card-body">
            <%= render coin %>
            <p>
              <%= link_to "Show this coin", coin, class: "btn btn-primary" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<p class="text-center mt-4">
  <%= link_to "New coin", new_coin_path, class: "btn btn-success" %>
</p>

app/views/coins/new.html.erb
<% content_for :title, "New coin" %>

<div class="container mt-4">
    <h1 class="text-primary">New Coin</h1>

    <div class="card p-4 shadow-sm mt-3">
        <%= render "form", coin: @coin %>
    </div>

    <div class="mt-4">
        <%= link_to "Back to coins", coins_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
    <%= render @coin %>

    <div class="mt-3">
        <%= link_to "Edit this coin", edit_coin_path(@coin), class: "btn btn-warning" %> |
        <%= link_to "Back to coins", coins_path, class: "btn btn-secondary" %>
    </div>

    <div class="mt-3">
        <%= button_to "Destroy this coin", @coin, method: :delete, class: "btn btn-danger" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crypto Wallet" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, class: "needs-validation") do |form| %>
  <% if mining_type.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining type from being saved:</h2>
      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :acronym, class: "form-label" %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit "Save Mining Type", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Description:</th>
      <th>Acronym:</th>
    </tr>
  </thead>

  <tbody>
    <th><%= mining_type.description %></th>
    <th><%= mining_type.acronym %></th>
  </tbody>
</table>

app/views/mining_types/edit.html.erb
<% content_for :title, "Editing mining type" %>

<div class="container mt-4">
    <h1 class="text-primary">Editing Mining Type</h1>

    <div class="card p-4 shadow-sm mt-3">
        <%= render "form", mining_type: @mining_type %>
    </div>

    <div class="mt-4">
        <%= link_to "Show this mining type", @mining_type, class: "btn btn-info" %> |
        <%= link_to "Back to mining types", mining_types_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Mining types" %>

<h1 class="text-center text-primary">Mining Types</h1>

<div id="mining_types" class="container mt-4">
  <div class="row">
    <% @mining_types.each do |mining_type| %>
      <div class="col-md-4">
        <div class="card shadow-sm p-3 mb-4 bg-white rounded">
          <div class="card-body">
            <%= render mining_type %>
            <p>
              <%= link_to "Show this mining type", mining_type, class: "btn btn-info" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<p class="text-center mt-4">
  <%= link_to "New mining type", new_mining_type_path, class: "btn btn-success" %>
</p>

app/views/mining_types/new.html.erb
<% content_for :title, "New mining type" %>

<div class="container mt-4">
    <h1 class="text-primary">New Mining Type</h1>

    <div class="card p-4 shadow-sm mt-3">
        <%= render "form", mining_type: @mining_type %>
    </div>

    <div class="mt-4">
        <%= link_to "Back to mining types", mining_types_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
    <%= render @mining_type %>

    <div class="mt-3">
        <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type), class: "btn btn-warning" %> |
        <%= link_to "Back to mining types", mining_types_path, class: "btn btn-secondary" %>
    </div>

    <div class="mt-3">
        <%= button_to "Destroy this mining type", @mining_type, method: :delete, class: "btn btn-danger" %>
    </div>
</div>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", coins_path, class:"btn btn-primary btn-lg", role:"button" %>
<%= link_to "#{MiningType.model_name.human}", mining_types_path, class:"btn btn-primary btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="container mt-5">
    <div class="jumbotron text-center p-5 bg-light shadow-sm rounded">
        <h1 class="display-3">Bem vindo, <strong><%= @meu_nome %></strong>!</h1>
        <h3 class="mt-3"><strong>Data: </strong><%= data_br(Date.today) %></h3>
        <div class="mt-4">
            <%= render "menu" %>
        </div>
    </div>
</div>